---
- hosts: all
  become: yes
  tasks:
   
   - name: disable SELinux
     shell: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled


   - name: Disable IPv6 with sysctl
     sysctl: name={{ item }} value=1 state=present
     with_items:
       - net.ipv6.conf.all.disable_ipv6
       - net.ipv6.conf.default.disable_ipv6
       - net.ipv6.conf.lo.disable_ipv6

   - name: RedHat | disable ipv6 in sysconfig/network
     blockinfile:
       path: /etc/sysconfig/network
       block: |
         NETWORKING_IPV6=NO
     notify:
       - restart network
     when: ansible_os_family == 'CentOS'

   - name: generate ssh keys
     shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
     args:
       creates: /root/.ssh/id_rsa
   - name: Upgrade the Machine
     yum:
       name: '*'
       state: latest

   - name: Check for reboot hint.
     shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
     ignore_errors: true
     register: reboot_hint

   - name: Rebooting ...
     command: shutdown -r now "Reboot required for updated kernel"
     async: 0
     poll: 0
     sudo: true
     ignore_errors: true
     when: reboot_hint.stdout.find("reboot") != -1
     register: rebooting

   - name: Wait for thing to reboot...
     pause: seconds=45
     when: rebooting|changed
     
   - name: Enable EPEL Rpository
     #shell: yum install epel-release -y
     yum:
       name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
       state: present

   - name: Import EPEL Rpository key
     rpm_key:
       key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
       state: present

   - name: Install Java
     yum:
       name: java
       state: latest

   - name: Install Java-Devel
     yum:
       name: java-devel
       state: latest
   


- hosts: slave
  become: yes
  tasks:
   - name: install maven
     yum:
       name: maven
       state: latest

   - name: install maven
     yum:
       name: git
       state: latest

   - name: add self authorization key
     shell: cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

- hosts: jenkins
  become: yes
  tasks:
   - name: Add Jenkins Repository
     get_url:
       url: https://pkg.jenkins.io/redhat/jenkins.repo
       dest: /etc/yum.repos.d/

   - name: Import Jenkins Repo Keys
     rpm_key:
       key: https://pkg.jenkins.io/redhat/jenkins.io.key
       state: present

   - name: Install Jenkins
     yum:
       name: jenkins
       state: latest

   - name: enable jenkins service is started and enabled
     systemd:
       name: jenkins
       enabled: yes
       state: started

   - name: Create Directory known_hosts for slave nodes
     file: 
       path: /var/lib/jenkins/.ssh
       state: directory 

   - name: Scan Slave ssh key  
     shell:  ssh-keyscan -H 10.80.41.217 >> /var/lib/jenkins/.ssh/known_hosts


- hosts: docker 
  become: yes
  tasks:

   - name: Add Docker Repository
     get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/

   - name: Install Docker-ce
     yum:
       name: 
         - yum-utils
         - device-mapper-persistent-data
         - python-pip
         - docker-ce
       state: latest
   
   - name: adding root user to group docker
     user:
       name: root
       groups: docker
       append: yes

   - name: upgrade pip
     pip:
       name: pip
       state: latest

   - name: enable docker service is started and enabled
     systemd:
       name: docker
       enabled: yes
       state: started

- hosts: tomcat 
  become: yes
  tasks:

   - name: Download Tomcat
     get_url: 
        url: http://10.80.40.21/shared/tomcat/tomcat7.tar
        dest: /tmp

   - name: Extract the Tomcat
     unarchive:
        src: /tmp/tomcat7.tar
        dest: /opt/
        remote_src: yes
   
   - name: Start Tomcat Service
     shell: /opt/tomcat7/bin/startup.sh
